site_name: Stemmabench
site_url: https://example.com/
nav:
  - Home: index.md
  - Variant configuration: variants.md
  - Outputs: outputs.md
  - Algorithms: algorithms.md
  - About: about.md

theme:
  name: material
  features:
    - content.code.annotate
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - section-index

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.details
  - attr_list